// app/predicted-locations/page.tsx
'use client';

import React, { useState } from 'react';
import {
  Search,
  Bell,
  Shield,
  MapPin,
  ChevronDown,
  Calendar,
  Download,
  ChevronLeft,
  ChevronRight,
  Navigation,
  Radar,
  Radio,
  Zap,
  Target,
  Crosshair,
  AlertCircle,
  X
} from 'lucide-react';

// --- MOCK PREDICTED LOCATIONS DATA ---
const PREDICTED_LOCATIONS_DATA = [
  {
    id: 'LOC-2026-901',
    zoneName: 'Chandni Chowk ATM Hub Cluster',
    city: 'New Delhi, DL',
    coordinates: { lat: 28.6506, lng: 77.2303, grid: '28.65° N, 77.23° E' },
    threatLevel: 'Critical',
    probabilityScore: '94%',
    predictedTimeframe: 'Next 2 Hours (07:00 PM - 09:00 PM)',
    predictedActivity: 'Mule Cash Withdrawal & Rapid ATM Drain',
    associatedCase: 'CAS-2026-0891 (Phishing Campaign)',
    targetATMCount: 6,
    historicalMatch: '88% match with previous cash-out sequence',
    description: 'Predictive spatial model identified a high probability of physical cash withdrawal based on sequential victim account transfers logged in the past 45 minutes.',
    surveillanceStatus: 'Patrol Vector Dispatched',
    nearbyUnits: ['PCR Unit #12 (1.2 km away)', 'Special Cell Sub-Station #4 (2.8 km away)']
  },
  {
    id: 'LOC-2026-902',
    zoneName: 'Rohini Sector 11 Cyber Cafe Arcades',
    city: 'New Delhi, DL',
    coordinates: { lat: 28.7153, lng: 77.1171, grid: '28.71° N, 77.11° E' },
    threatLevel: 'High',
    probabilityScore: '81%',
    predictedTimeframe: 'Next 6 Hours',
    predictedActivity: 'Secondary OTP Hijack & SIM Swap Operation',
    associatedCase: 'CAS-2026-0885 (ATM Skimming)',
    targetATMCount: 2,
    historicalMatch: '76% match with active Jamtara network movements',
    description: 'Geospatial clustering analysis detected multiple unauthorized device ping bursts within an unregistered telecom sector tower cell.',
    surveillanceStatus: 'Under Electronic Monitoring',
    nearbyUnits: ['Rohini Sector 11 Local Station (0.8 km away)']
  },
  {
    id: 'LOC-2026-903',
    zoneName: 'Cyber City Corporate Tower Kiosks',
    city: 'Gurugram, HR',
    coordinates: { lat: 28.495, lng: 77.0895, grid: '28.49° N, 77.08° E' },
    threatLevel: 'Medium',
    probabilityScore: '67%',
    predictedTimeframe: 'Next 12 Hours',
    predictedActivity: 'Offshore Crypto Gateway P2P Settlement',
    associatedCase: 'CAS-2026-0870 (Deepfake Extortion)',
    targetATMCount: 4,
    historicalMatch: '62% match with weekend liquidity drains',
    description: 'AI model flagged an unusual velocity of low-value wallet registrations originating from shared public Wi-Fi hotspots in commercial hubs.',
    surveillanceStatus: 'Standby Monitoring',
    nearbyUnits: ['Cyber Crime Unit Gurugram (3.5 km away)']
  },
  {
    id: 'LOC-2026-904',
    zoneName: 'Kolkata Sector V Tech Hub',
    city: 'Kolkata, WB',
    coordinates: { lat: 22.5726, lng: 88.431, grid: '22.57° N, 88.43° E' },
    threatLevel: 'Low',
    probabilityScore: '45%',
    predictedTimeframe: '24 Hours Window',
    predictedActivity: 'Mule Account Onboarding Burst',
    associatedCase: 'CAS-2026-0812 (Bulk Micro-Deposits)',
    targetATMCount: 3,
    historicalMatch: '49% match with recurring monthly patterns',
    description: 'Low-confidence anomaly score generated by regional bank node telemetry indicating potential fake documentation submission.',
    surveillanceStatus: 'Passive Logging',
    nearbyUnits: ['Bidhannagar Patrol Division (2.1 km away)']
  }
];

export default function PredictedLocationsDashboard() {
  // --- STATE MANAGEMENT ---
  const [locations, setLocations] = useState(PREDICTED_LOCATIONS_DATA);
  // `!` throughout this file: `noUncheckedIndexedAccess` is on, and these are
  // module-level literals that are never emptied, so the element does exist.
  const [selectedLocation, setSelectedLocation] = useState<(typeof PREDICTED_LOCATIONS_DATA)[0]>(
    PREDICTED_LOCATIONS_DATA[0]!
  );

  // Filters State
  const [searchQuery, setSearchQuery] = useState('');
  const [threatFilter, setThreatFilter] = useState('All');
  const [timeframeFilter, setTimeframeFilter] = useState('All');
  const [dateRange, setDateRange] = useState('05 Sep 2026 (Live Window)');

  // Pagination State
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 3;

  // Modal State for Investigation Dispatch
  const [isDispatchModalOpen, setIsDispatchModalOpen] = useState(false);
  const [dispatchStatus, setDispatchStatus] = useState<Record<string, boolean>>({});

  // Filtering Logic
  const filteredLocations = locations.filter((loc) => {
    const matchesSearch =
      loc.zoneName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      loc.city.toLowerCase().includes(searchQuery.toLowerCase()) ||
      loc.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      loc.associatedCase.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesThreat = threatFilter === 'All' || loc.threatLevel === threatFilter;

    return matchesSearch && matchesThreat;
  });

  // Pagination Logic
  const totalPages = Math.ceil(filteredLocations.length / itemsPerPage) || 1;
  const paginatedLocations = filteredLocations.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  // Threat Badge Helper
  const getThreatBadge = (level: string) => {
    switch (level) {
      case 'Critical':
        return 'bg-rose-500/10 text-rose-400 border-rose-500/30 font-bold animate-pulse';
      case 'High':
        return 'bg-amber-500/10 text-amber-400 border-amber-500/30 font-semibold';
      case 'Medium':
        return 'bg-blue-500/10 text-blue-400 border-blue-500/30';
      default:
        return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30';
    }
  };

  // Toggle Patrol Dispatch
  const handleToggleDispatch = (locId: string) => {
    setDispatchStatus((prev) => ({ ...prev, [locId]: true }));
    setIsDispatchModalOpen(false);
  };

  return (
    <div className="flex h-full bg-paper text-ink-700 overflow-hidden">
      {/* Main Workspace */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Read before anything below it: a caveat under the numbers is a
            caveat nobody reaches. */}
        {/* Top Header Bar */}
        <header className="h-16 bg-paper border-b border-line flex items-center justify-between px-6 shrink-0">
          <div className="relative w-96">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-ink-500" />
            <input
              type="text"
              placeholder="Search predicted zones, cities, or case IDs..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-paper border border-line rounded-lg pl-9 pr-8 py-1.5 text-xs text-ink-700 placeholder-slate-500 focus:outline-none focus:border-blue-500 transition-colors"
            />
            <span className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[10px] bg-raised text-ink-500 px-1.5 py-0.5 rounded border border-line-strong">
              ⌘K
            </span>
          </div>

          <div className="flex items-center space-x-4">
            <button className="relative p-2 text-ink-500 hover:text-ink-900 rounded-lg hover:bg-raised transition-colors">
              <Bell className="w-5 h-5" />
              <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-rose-500 rounded-full animate-ping"></span>
              <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-rose-500 rounded-full"></span>
            </button>
            <div className="flex items-center space-x-3 pl-4 border-l border-line">
              <div className="w-8 h-8 rounded-full bg-raised border border-line-strong flex items-center justify-center font-bold text-xs text-ink-700">
                A
              </div>
              <div>
                <p className="text-xs font-semibold text-ink-700">Inspector</p>
                <p className="text-[10px] text-ink-500">Delhi Cyber Cell</p>
              </div>
            </div>
          </div>
        </header>

        <p className="mx-6 mt-4 rounded-md border border-line bg-surface px-3 py-2 text-[11px] italic text-ink-500">
          Mock predictions for interface development. No Tier 2 ranker is trained and
          nothing here is calibrated, so every score on this page is illustrative — live
          rankings come only from a validated model run.
        </p>

        {/* Dashboard Main Canvas */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Title & Quick Controls Bar */}
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex items-center space-x-3">
                <h2 className="text-2xl font-bold text-ink-900 tracking-tight">Predicted Locations Engine</h2>
                <span className="bg-rose-500/10 text-rose-400 text-xs px-2.5 py-0.5 rounded-full border border-rose-500/30 font-semibold flex items-center space-x-1">
                  <Radio className="w-3 h-3 animate-pulse text-rose-500" />
                  <span>PREDICTIVE AI ACTIVE</span>
                </span>
              </div>
              <p className="text-xs text-ink-500 mt-1">
                Spatial machine learning forecasting potential cash-out clusters, ATM drains, and mule movements.
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-3">
              {/* Date Filter */}
              <div className="flex items-center bg-paper border border-line rounded-lg px-3 py-1.5 text-xs text-ink-700 space-x-2">
                <Calendar className="w-3.5 h-3.5 text-ink-500" />
                <span>{dateRange}</span>
              </div>

              {/* Threat Level Filter */}
              <div className="relative">
                <select
                  value={threatFilter}
                  onChange={(e) => setThreatFilter(e.target.value)}
                  className="bg-paper border border-line text-xs text-ink-700 rounded-lg px-3 py-1.5 appearance-none pr-8 focus:outline-none focus:border-blue-500 cursor-pointer"
                >
                  <option value="All">All Threat Levels</option>
                  <option value="Critical">Critical Threat</option>
                  <option value="High">High Threat</option>
                  <option value="Medium">Medium Threat</option>
                  <option value="Low">Low Threat</option>
                </select>
                <ChevronDown className="w-3.5 h-3.5 absolute right-2.5 top-1/2 -translate-y-1/2 text-ink-500 pointer-events-none" />
              </div>

              {/* Export Report Button */}
              <button className="bg-blue-600 hover:bg-blue-500 text-ink-900 px-3.5 py-1.5 rounded-lg text-xs font-semibold flex items-center space-x-1.5 shadow-lg shadow-blue-950/30 transition-all">
                <Download className="w-3.5 h-3.5" />
                <span>Export Patrol Vector</span>
              </button>
            </div>
          </div>

          {/* Master-Detail Map Canvas Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* Left Column: Interactive Map Visualization Frame */}
            <div className="lg:col-span-7 bg-paper border border-line rounded-xl p-5 relative min-h-[580px] flex flex-col justify-between overflow-hidden">
              {/* Map Header Overlay */}
              <div className="flex items-center justify-between border-b border-line pb-3 z-10 bg-paper/90 backdrop-blur">
                <div className="flex items-center space-x-2">
                  <Radar className="w-4 h-4 text-blue-400 animate-spin" style={{ animationDuration: '8s' }} />
                  <h3 className="font-semibold text-ink-900 text-xs uppercase tracking-wider">
                    Geospatial Heatmap Radar (Delhi NCR Hub)
                  </h3>
                </div>
                <div className="flex items-center space-x-2 text-[10px] text-ink-500">
                  <span className="flex items-center space-x-1">
                    <span className="w-2 h-2 rounded-full bg-rose-500"></span>
                    <span>High Probability</span>
                  </span>
                  <span className="flex items-center space-x-1 pl-2">
                    <span className="w-2 h-2 rounded-full bg-amber-500"></span>
                    <span>Medium</span>
                  </span>
                </div>
              </div>

              {/* Simulated Dark-Mode Interactive Map Canvas */}
              <div className="absolute inset-0 top-14 bottom-12 bg-[#05070D] opacity-90 flex items-center justify-center overflow-hidden">
                {/* SVG Tactical Grid Graphic */}
                <svg className="w-full h-full absolute inset-0 stroke-slate-800/40" width="100%" height="100%">
                  <defs>
                    <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
                      <path d="M 40 0 L 0 0 0 40" fill="none" strokeWidth="0.5" />
                    </pattern>
                  </defs>
                  <rect width="100%" height="100%" fill="url(#grid)" />
                </svg>

                {/* Tactical Radar Ring Animations */}
                <div className="absolute w-96 h-96 border border-blue-500/10 rounded-full animate-ping pointer-events-none" style={{ animationDuration: '4s' }}></div>
                <div className="absolute w-[500px] h-[500px] border border-line rounded-full pointer-events-none"></div>

                {/* Clickable Map Nodes overlayed on tactical grid */}
                <div className="relative w-full h-full">
                  {/* Node 1: Chandni Chowk (Critical) */}
                  <div
                    onClick={() => setSelectedLocation(PREDICTED_LOCATIONS_DATA[0]!)}
                    className="absolute top-[32%] left-[48%] -translate-x-1/2 -translate-y-1/2 cursor-pointer group"
                  >
                    <div className="relative flex items-center justify-center">
                      <span className="absolute w-10 h-10 bg-rose-500/20 rounded-full animate-ping"></span>
                      <div
                        className={`w-7 h-7 rounded-full bg-rose-600 border-2 border-white flex items-center justify-center shadow-lg shadow-rose-950/80 transition-transform group-hover:scale-125 ${
                          selectedLocation.id === 'LOC-2026-901' ? 'ring-4 ring-rose-500/40 scale-110' : ''
                        }`}
                      >
                        <Target className="w-3.5 h-3.5 text-ink-900" />
                      </div>
                      {/* Tooltip Badge */}
                      <div className="absolute left-8 top-0 bg-paper border border-line-strong px-2 py-1 rounded shadow-xl whitespace-nowrap text-[10px]">
                        <p className="font-bold text-ink-900">Chandni Chowk Cluster</p>
                        <p className="text-rose-400 font-mono">94% Risk Score</p>
                      </div>
                    </div>
                  </div>

                  {/* Node 2: Rohini Sector 11 (High) */}
                  <div
                    onClick={() => setSelectedLocation(PREDICTED_LOCATIONS_DATA[1]!)}
                    className="absolute top-[20%] left-[28%] -translate-x-1/2 -translate-y-1/2 cursor-pointer group"
                  >
                    <div className="relative flex items-center justify-center">
                      <div
                        className={`w-6 h-6 rounded-full bg-amber-500 border-2 border-white flex items-center justify-center shadow-lg transition-transform group-hover:scale-125 ${
                          selectedLocation.id === 'LOC-2026-902' ? 'ring-4 ring-amber-500/40 scale-110' : ''
                        }`}
                      >
                        <Crosshair className="w-3 h-3 text-black" />
                      </div>
                      <div className="absolute left-7 top-0 bg-paper border border-line-strong px-2 py-1 rounded shadow-xl whitespace-nowrap text-[10px]">
                        <p className="font-bold text-ink-900">Rohini Sector 11</p>
                        <p className="text-amber-400 font-mono">81% Risk Score</p>
                      </div>
                    </div>
                  </div>

                  {/* Node 3: Gurugram Cyber City (Medium) */}
                  <div
                    onClick={() => setSelectedLocation(PREDICTED_LOCATIONS_DATA[2]!)}
                    className="absolute top-[68%] left-[38%] -translate-x-1/2 -translate-y-1/2 cursor-pointer group"
                  >
                    <div className="relative flex items-center justify-center">
                      <div
                        className={`w-5 h-5 rounded-full bg-blue-500 border border-white flex items-center justify-center shadow-lg transition-transform group-hover:scale-125 ${
                          selectedLocation.id === 'LOC-2026-903' ? 'ring-4 ring-blue-500/40 scale-110' : ''
                        }`}
                      >
                        <MapPin className="w-3 h-3 text-ink-900" />
                      </div>
                      <div className="absolute left-6 top-0 bg-paper border border-line-strong px-2 py-1 rounded shadow-xl whitespace-nowrap text-[10px]">
                        <p className="font-bold text-ink-900">Gurugram Cyber City</p>
                        <p className="text-blue-400 font-mono">67% Risk Score</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Map Canvas Footer Info */}
              <div className="border-t border-line pt-3 flex items-center justify-between text-xs text-ink-500 z-10 bg-paper/90">
                <span>Active Target Nodes Visualized: <strong className="text-ink-700">3 in NCR Vector</strong></span>
                <span>Coordinates Reference: <strong className="text-ink-700 font-mono">WGS-84 Grid</strong></span>
              </div>
            </div>

            {/* Right Column: Predicted Zone Detail & Investigation Panel */}
            <div className="lg:col-span-5 bg-paper border border-line rounded-xl p-5 space-y-5 flex flex-col justify-between h-full min-h-[580px]">
              {selectedLocation ? (
                <>
                  <div className="space-y-4">
                    {/* Header Detail */}
                    <div className="border-b border-line pb-3 flex items-center justify-between">
                      <div>
                        <span className="text-[10px] font-mono text-blue-400 font-bold">{selectedLocation.id}</span>
                        <h3 className="font-bold text-ink-900 text-base leading-tight">
                          {selectedLocation.zoneName}
                        </h3>
                        <p className="text-xs text-ink-500">{selectedLocation.city}</p>
                      </div>
                      <span className={`text-xs px-2.5 py-0.5 rounded border ${getThreatBadge(selectedLocation.threatLevel)}`}>
                        {selectedLocation.threatLevel}
                      </span>
                    </div>

                    {/* Risk & Probability Score Banner */}
                    <div className="bg-paper p-3.5 rounded-xl border border-line flex items-center justify-between">
                      <div className="space-y-0.5">
                        <span className="text-ink-500 text-[10px]">
                          Illustrative score — not a model output
                        </span>
                        <p className="font-mono text-2xl font-extrabold text-rose-400">
                          {selectedLocation.probabilityScore}
                        </p>
                      </div>
                      <div className="text-right space-y-0.5">
                        <span className="text-ink-500 text-[10px]">Expected Window</span>
                        <p className="text-xs font-semibold text-ink-700">{selectedLocation.predictedTimeframe}</p>
                      </div>
                    </div>

                    {/* Metadata Breakdown */}
                    <div className="space-y-2.5 text-xs">
                      <div className="bg-paper p-3 rounded-lg border border-line space-y-1">
                        <span className="text-ink-500 text-[10px]">Predicted Threat Activity</span>
                        <p className="font-bold text-ink-700">{selectedLocation.predictedActivity}</p>
                      </div>

                      <div className="grid grid-cols-2 gap-2">
                        <div className="bg-paper p-2.5 rounded-lg border border-line space-y-0.5">
                          <span className="text-ink-500 text-[10px]">Target Kiosks / ATMs</span>
                          <p className="font-semibold text-ink-700">{selectedLocation.targetATMCount} Hotspot Terminals</p>
                        </div>
                        <div className="bg-paper p-2.5 rounded-lg border border-line space-y-0.5">
                          <span className="text-ink-500 text-[10px]">Grid Coordinates</span>
                          <p className="font-mono text-blue-400 text-[11px] truncate">{selectedLocation.coordinates.grid}</p>
                        </div>
                      </div>

                      <div className="bg-paper p-3 rounded-lg border border-line space-y-1">
                        <span className="text-ink-500 text-[10px]">Associated Active Investigation</span>
                        <p className="font-semibold text-blue-400">{selectedLocation.associatedCase}</p>
                        <p className="text-[10px] text-ink-500">{selectedLocation.historicalMatch}</p>
                      </div>

                      <div className="bg-paper p-3 rounded-lg border border-line space-y-1">
                        <span className="text-ink-500 text-[10px]">Nearby Response Units</span>
                        <div className="space-y-1">
                          {selectedLocation.nearbyUnits.map((unit, idx) => (
                            <p key={idx} className="text-ink-700 text-[11px] flex items-center space-x-1.5">
                              <Navigation className="w-3 h-3 text-emerald-400" />
                              <span>{unit}</span>
                            </p>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Investigation Dispatch & Patrol Controls */}
                  <div className="pt-4 border-t border-line space-y-2">
                    <span className="text-[10px] text-ink-500 block">Patrol Vector & Interception Control</span>

                    <button
                      onClick={() => setIsDispatchModalOpen(true)}
                      className={`w-full py-2.5 rounded-lg text-xs font-semibold flex items-center justify-center space-x-2 transition-all ${
                        dispatchStatus[selectedLocation.id]
                          ? 'bg-emerald-600 text-ink-900'
                          : 'bg-rose-600 hover:bg-rose-500 text-ink-900 shadow-lg shadow-rose-950/30'
                      }`}
                    >
                      <Zap className="w-4 h-4" />
                      <span>
                        {dispatchStatus[selectedLocation.id]
                          ? 'Patrol Intercept Unit Dispatched'
                          : 'Dispatch Ground Intercept Patrol'}
                      </span>
                    </button>
                  </div>
                </>
              ) : (
                <div className="flex flex-col items-center justify-center h-full text-ink-500 text-xs">
                  <AlertCircle className="w-8 h-8 mb-2 stroke-1" />
                  <span>Select a predicted zone from the map radar to inspect AI forecasts.</span>
                </div>
              )}
            </div>
          </div>

          {/* Paginated List Strip for All Predicted Hits */}
          <div className="bg-paper border border-line rounded-xl p-4 space-y-3">
            <div className="flex items-center justify-between border-b border-line pb-3">
              <h3 className="font-semibold text-ink-900 text-xs">All AI Spatial Predictions Directory</h3>
              <span className="text-[10px] text-ink-500">Showing {paginatedLocations.length} of {filteredLocations.length} hits</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              {paginatedLocations.map((loc) => (
                <div
                  key={loc.id}
                  onClick={() => setSelectedLocation(loc)}
                  className={`bg-paper border rounded-xl p-3.5 cursor-pointer space-y-2 transition-all ${
                    selectedLocation.id === loc.id
                      ? 'border-blue-500 ring-1 ring-blue-500/40 bg-raised/20'
                      : 'border-line hover:border-line-strong'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-[10px] text-blue-400 font-bold">{loc.id}</span>
                    <span className={`text-[10px] px-2 py-0.5 rounded border ${getThreatBadge(loc.threatLevel)}`}>
                      {loc.threatLevel}
                    </span>
                  </div>
                  <h4 className="font-bold text-ink-900 text-xs truncate">{loc.zoneName}</h4>
                  <div className="flex items-center justify-between text-[10px] text-ink-500 border-t border-line pt-2">
                    <span>Probability: <strong className="text-rose-400">{loc.probabilityScore}</strong></span>
                    <span>{loc.city}</span>
                  </div>
                </div>
              ))}
            </div>

            {/* Pagination Controls */}
            <div className="flex items-center justify-between text-xs text-ink-500 pt-2">
              <span>
                Page {currentPage} of {totalPages}
              </span>
              <div className="flex items-center space-x-1">
                <button
                  disabled={currentPage === 1}
                  onClick={() => setCurrentPage((p) => Math.max(p - 1, 1))}
                  className="p-1 bg-paper border border-line rounded hover:bg-raised disabled:opacity-30"
                >
                  <ChevronLeft className="w-4 h-4" />
                </button>
                <button
                  disabled={currentPage === totalPages}
                  onClick={() => setCurrentPage((p) => Math.min(p + 1, totalPages))}
                  className="p-1 bg-paper border border-line rounded hover:bg-raised disabled:opacity-30"
                >
                  <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Dispatch Patrol Order Confirmation Modal */}
      {isDispatchModalOpen && selectedLocation && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-paper border border-line rounded-2xl max-w-md w-full p-6 space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-line pb-3">
              <h3 className="font-bold text-ink-900 text-base flex items-center space-x-2">
                <Shield className="w-5 h-5 text-rose-500" />
                <span>Confirm Patrol Intercept Order</span>
              </h3>
              <button onClick={() => setIsDispatchModalOpen(false)} className="text-ink-500 hover:text-ink-700">
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-3 text-xs text-ink-700">
              <p>
                You are issuing an immediate response vector order for{' '}
                <strong className="text-ink-900">{selectedLocation.zoneName}</strong> under case{' '}
                <strong className="text-blue-400 font-mono">{selectedLocation.associatedCase}</strong>.
              </p>

              <div className="bg-paper p-3 rounded-lg border border-line space-y-1">
                <span className="text-ink-500 text-[10px]">Primary Assigned Unit</span>
                <p className="font-bold text-ink-900">{selectedLocation.nearbyUnits[0]}</p>
                <span className="text-ink-500 text-[10px]">Predicted Window: {selectedLocation.predictedTimeframe}</span>
              </div>
            </div>

            <div className="flex items-center justify-end space-x-3 pt-3 border-t border-line text-xs">
              <button
                onClick={() => setIsDispatchModalOpen(false)}
                className="px-4 py-2 rounded-lg bg-raised text-ink-700 hover:bg-slate-700"
              >
                Cancel
              </button>
              <button
                onClick={() => handleToggleDispatch(selectedLocation.id)}
                className="px-4 py-2 rounded-lg bg-rose-600 text-ink-900 hover:bg-rose-500 font-semibold"
              >
                Confirm Patrol Dispatch
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}