"""Rank cash-out zones for a complaint, and measure whether it beats chance.

    python -m ml.probe.run

The question, stated precisely: at the moment a complaint is filed, ATLAS knows
the victim's zone, the typology and the time. It does not know where the money
will be withdrawn. Can it rank zones such that the true cash-out zone appears
near the top more often than area-proportional flagging would put it there?

Two rankers are compared on a **temporal** split — train on the earlier half of
scenarios, test on the later half. A random split would let the model learn from
cash-outs that had not happened yet, which is the whole failure this project is
built to avoid.

    prior      how often each zone is a cash-out zone at all, historically.
               No conditioning on the complaint. This is the baseline to beat.

    conditional  how often each zone is a cash-out zone *given the victim's
               zone and the typology*, backing off to the prior when a cell of
               the table is unseen.

The headline is PAI — uplift over area-proportional flagging — never raw
accuracy. Reported per K, because flagging one zone and flagging ten are
different operational decisions with different costs.
"""

from __future__ import annotations

import asyncio
import math
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from random import Random
from urllib.parse import quote_plus

from sqlalchemy import text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "apps" / "api"))
sys.path.insert(0, str(REPO))

from ml.evaluation.metrics import prediction_accuracy_index


@dataclass(frozen=True)
class Case:
    """What is knowable at complaint time, plus the label.

    ``cash_out_zone`` is the answer. It is carried on the same object only
    because this is an offline evaluation script; nothing that scores a live
    complaint may hold both.
    """

    fraud_initiated_at: datetime
    typology: str
    victim_zone: str | None
    cash_out_zone: str | None


def _sim_database_url() -> str:
    from atlas.core.config import get_settings

    s = get_settings()
    return (
        f"postgresql+asyncpg://{quote_plus('atlas_sim')}:{quote_plus(s.db_password)}"
        f"@{s.db_host}:{s.db_port}/{s.db_name}"
    )


async def load_cases(dataset_version: str) -> list[Case]:
    engine = create_async_engine(_sim_database_url())
    factory = async_sessionmaker(engine, expire_on_commit=False)
    try:
        async with factory() as session:
            rows = await session.execute(
                text(
                    "SELECT s.fraud_initiated_at, s.typology, s.victim_jurisdiction, "
                    "       e.endpoint_jurisdiction "
                    "FROM truth.scenario s "
                    "JOIN truth.cash_out_event e ON e.scenario_id = s.id "
                    "WHERE s.dataset_version = :v "
                    "ORDER BY s.fraud_initiated_at"
                ),
                {"v": dataset_version},
            )
            return [Case(*row) for row in rows]
    finally:
        await engine.dispose()


def diagnose_dataset(cases: list[Case], zones: list[str]) -> bool:
    """Check the dataset contains signal to find, before scoring anything against it.

    A ranker cannot beat chance on labels that were generated by chance, and a
    PAI of 1.0 then measures the generator rather than the approach. Reporting
    that as "location is unpredictable" would be the most expensive wrong
    conclusion available.

    Returns True when the dataset looks usable.
    """
    labelled = [c for c in cases if c.cash_out_zone and c.victim_zone]
    usable = True
    print("\n  dataset diagnostics")

    # 1. Is the cash-out zone independent of the victim's zone?
    same = sum(1 for c in labelled if c.cash_out_zone == c.victim_zone)
    expected = len(labelled) / len(zones)
    print(
        f"    victim zone == cash-out zone: {same}/{len(labelled)} "
        f"(chance would be ~{expected:.0f})"
    )
    if abs(same - expected) < max(3.0, 0.5 * math.sqrt(expected)):
        print(
            "      ↳ indistinguishable from chance: the generator is not linking them"
        )
        usable = False

    # 2. Does knowing the case tell you anything about the label?
    #
    # This replaced a check on how concentrated the *marginal* label distribution
    # was — "the top quartile of zones must hold more than 35% of cash-outs". That
    # check was wrong in both directions and it is worth saying why, because
    # loosening a gate is the move that needs the most scrutiny.
    #
    # It produced false negatives: cash-out is local to the mule, mules are
    # concentrated in a handful of districts, and those districts are adjacent, so
    # the marginal distribution flattens across a cluster while the conditional
    # structure is strong. It plateaued at ~34% under every plausible setting of
    # the locality decay.
    #
    # It also produced false positives, which is the worse failure: a generator
    # that put every cash-out in Jamtara regardless of the case would score 100%
    # and be perfectly unlearnable per case.
    #
    # Mutual information asks the question Tier 1 actually needs answered — does
    # conditioning on the case change the distribution over zones — and it is
    # scored against a label-shuffled control, so "how much is chance at this
    # sample size" is measured rather than assumed.
    # `labelled` is already filtered on both being present; the narrowing is for
    # the type checker, which cannot see that through the comprehension above.
    conditioned = [
        (c.victim_zone, c.cash_out_zone)
        for c in labelled
        if c.victim_zone is not None and c.cash_out_zone is not None
    ]
    observed = _normalised_mutual_information(conditioned)
    control = _shuffled_control(conditioned)
    print(
        f"    NMI(victim zone -> cash-out zone): {observed:.4f} "
        f"(shuffled control {control:.4f})"
    )
    if observed < 2 * control:
        print("      ↳ knowing the case says little about the zone: nothing to rank on")
        usable = False

    # 3. Is there any spread in time to split on?
    distinct_times = len({c.fraud_initiated_at for c in cases})
    print(
        f"    distinct fraud timestamps: {distinct_times} across {len(cases)} scenarios"
    )
    if distinct_times < 2:
        print(
            "      ↳ every scenario shares one timestamp; a temporal split is not possible"
        )
        usable = False

    return usable


def _normalised_mutual_information(pairs: list[tuple[str, str]]) -> float:
    """I(X;Y) / H(Y) — how much of the label's entropy the conditioner explains.

    Normalised so the number is comparable across datasets with different numbers
    of zones; raw mutual information grows with the label alphabet and would make
    a coarser geography look worse than a finer one for no reason.
    """
    n = len(pairs)
    if n == 0:
        return 0.0
    joint = Counter(pairs)
    left = Counter(a for a, _ in pairs)
    right = Counter(b for _, b in pairs)

    mi = sum(
        (c / n) * math.log((c / n) / ((left[a] / n) * (right[b] / n)))
        for (a, b), c in joint.items()
    )
    label_entropy = -sum((c / n) * math.log(c / n) for c in right.values())
    return mi / label_entropy if label_entropy > 0 else 0.0


def _shuffled_control(pairs: list[tuple[str, str]]) -> float:
    """The same statistic on shuffled labels — what chance looks like at this ``n``.

    Mutual information is biased upward on finite samples: two independent
    variables score above zero, and the bias grows as the sample shrinks or the
    alphabet grows. Comparing against a fixed threshold would therefore pass a
    small independent dataset. The control is the threshold.

    Seeded, so a diagnostic that decides whether numbers may be published does not
    itself change between runs.
    """
    labels = [b for _, b in pairs]
    Random(20260906).shuffle(labels)
    return _normalised_mutual_information(
        [(a, b) for (a, _), b in zip(pairs, labels, strict=True)]
    )


def rank_by_prior(train: list[Case], zones: list[str]) -> list[str]:
    """Zones ordered by how often they are a cash-out zone at all."""
    counts = Counter(c.cash_out_zone for c in train if c.cash_out_zone)
    return sorted(zones, key=lambda z: (-counts.get(z, 0), z))


def rank_conditional(
    train: list[Case], zones: list[str]
) -> dict[tuple[str, str], list[str]]:
    """Zones ordered per (victim zone, typology), backing off to the prior.

    The back-off matters more than the conditioning. Most (victim, typology)
    pairs are unseen in a dataset this size, and a ranker that returns an
    arbitrary order for them would score its own sparsity rather than its
    signal.
    """
    prior = rank_by_prior(train, zones)
    conditioned: dict[tuple[str, str], Counter[str]] = defaultdict(Counter)
    for c in train:
        if c.victim_zone and c.cash_out_zone:
            conditioned[(c.victim_zone, c.typology)][c.cash_out_zone] += 1

    table: dict[tuple[str, str], list[str]] = {}
    for key, counts in conditioned.items():
        seen = [z for z, _ in counts.most_common()]
        table[key] = seen + [z for z in prior if z not in counts]
    return table


def evaluate(
    name: str,
    test: list[Case],
    zones: list[str],
    ranking_for: object,
) -> None:
    """Report Recall@K and PAI at each K, for one ranker."""
    total_zones = len(zones)
    print(f"\n  {name}")
    print(f"    {'K':>3}  {'recall@K':>9}  {'PAI':>7}  {'area flagged':>13}")

    labelled = [c for c in test if c.cash_out_zone]
    for k in (1, 2, 3, 5):
        if k > total_zones:
            continue
        hits = 0
        for case in labelled:
            ranked = ranking_for(case)  # type: ignore[operator]
            if case.cash_out_zone in ranked[:k]:
                hits += 1

        area_fraction = k / total_zones
        pai = prediction_accuracy_index(
            hits=hits,
            total_hits=len(labelled),
            flagged_area=float(k),
            total_area=float(total_zones),
            h3_resolution=0,  # zones, not H3 cells — see the caveat in main()
        )
        print(
            f"    {k:>3}  {hits / len(labelled):>8.1%}  {pai.value:>7.2f}  {area_fraction:>12.1%}"
        )


async def main() -> int:
    cases = await load_cases("v1")
    if not cases:
        print("no scenarios in truth.v1 — run `python -m simulator --force` first")
        return 1

    zones = sorted({c.cash_out_zone for c in cases if c.cash_out_zone})
    split = len(cases) // 2
    train, test = cases[:split], cases[split:]

    print("probe on truth.v1")
    print(f"  {len(cases)} scenarios · {len(zones)} candidate zones")
    print(f"  temporal split: {len(train)} train / {len(test)} test")
    print(f"  train window ends {train[-1].fraud_initiated_at:%Y-%m-%d %H:%M}")
    print(f"  test  window starts {test[0].fraud_initiated_at:%Y-%m-%d %H:%M}")

    usable = diagnose_dataset(cases, zones)
    if not usable:
        print("\n  ── the dataset contains no signal to find ──")
        print("  Scoring a ranker against it would measure the generator, not the")
        print("  approach. A PAI of 1.0 here is the arithmetic of random labels, and")
        print("  reading it as 'cash-out location is unpredictable' would be the most")
        print("  expensive wrong conclusion available to this project.")
        print("\n  Cause: simulator/generators/endpoints.py::_zone_for_account returns")
        print("  rng.choice(ZONES), ignoring the `near` account it is passed. The")
        print("  cash-out zone is therefore independent of the money trail.")
        print("\n  Scoring anyway, for the record — but read nothing into it.")

    prior = rank_by_prior(train, zones)
    conditional = rank_conditional(train, zones)

    evaluate("baseline — historical zone frequency", test, zones, lambda c: prior)
    evaluate(
        "conditional — victim zone x typology, backing off to prior",
        test,
        zones,
        lambda c: conditional.get((c.victim_zone or "", c.typology), prior),
    )

    print("\n  PAI 1.0 means no better than flagging that share of area at random.")
    print("  Anything at or below 1.0 is a negative result and should be read as one.")
    print("\n  Caveats, all of which matter more than the numbers:")
    print("   · the dataset failed the Benford realism check (issue #45), so it is")
    print("     not validated and these numbers are not project metrics;")
    print("   · zones are administrative areas of unequal size, so 'area' here is")
    print("     a zone count, not true area — PAI at a fixed H3 resolution (ADR-011)")
    print("     is the comparable form and needs endpoint coordinates the simulator")
    print("     does not yet emit;")
    print("   · the separability gate has never run, so a feature could be leaking")
    print("     the label without anything catching it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
