"""feature store

Revision ID: 47a8554a2f45
Revises: 1950dbb695a5
Create Date: 2026-09-06 00:00:04.737965
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op


revision: str = '47a8554a2f45'
down_revision: str | None = '1950dbb695a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_value',
    sa.Column('subject_kind', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=96), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_kind', 'subject_id', 'feature_name', 'observed_at', name='uq_feature_value_point_in_time'),
    schema='features'
    )
    op.create_index('ix_feature_value_as_of', 'feature_value', ['subject_kind', 'subject_id', 'feature_name', 'observed_at'], unique=False, schema='features')
    op.create_index('ix_feature_value_name_observed', 'feature_value', ['feature_name', 'observed_at'], unique=False, schema='features')
    op.create_index(op.f('ix_features_feature_value_observed_at'), 'feature_value', ['observed_at'], unique=False, schema='features')

    # b1c2d3e4f5a6 ran `GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA features`
    # when the schema was empty, and set ALTER DEFAULT PRIVILEGES for SELECT
    # only. So the feature pipeline could read this table and not write it —
    # the one thing it exists to do.
    #
    # Granting on the table and fixing the default, so the next feature table
    # does not repeat this.
    op.execute("GRANT SELECT, INSERT ON features.feature_value TO atlas_features")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA features "
        "GRANT SELECT, INSERT ON TABLES TO atlas_features"
    )

    # The serving path reads features to score, and never writes them. A
    # prediction request that could append to the store would let inference
    # rewrite its own inputs.
    op.execute("REVOKE INSERT, UPDATE, DELETE ON features.feature_value FROM atlas_app")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_feature_value_observed_at'), table_name='feature_value', schema='features')
    op.drop_index('ix_feature_value_name_observed', table_name='feature_value', schema='features')
    op.drop_index('ix_feature_value_as_of', table_name='feature_value', schema='features')
    op.drop_table('feature_value', schema='features')
    # ### end Alembic commands ###
