"""phase 1: core domain model

Revision ID: a436cdfe30cd
Revises: 
Create Date: 2026-09-02 20:28:04.951045
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a436cdfe30cd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=64), nullable=True),
    sa.Column('actor_jurisdiction', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=96), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence', name='uq_audit_event_sequence'),
    schema='audit'
    )
    op.create_index('ix_audit_event_actor', 'audit_event', ['actor_id', 'occurred_at'], unique=False, schema='audit')
    op.create_index('ix_audit_event_occurred_at', 'audit_event', ['occurred_at'], unique=False, schema='audit')
    op.create_index('ix_audit_event_resource', 'audit_event', ['resource_type', 'resource_id'], unique=False, schema='audit')
    op.create_table('case',
    sa.Column('public_ref', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'TRIAGED', 'INVESTIGATING', 'ACTION_RECOMMENDED', 'ACTIONED', 'OUTCOME_RECORDED', 'CLOSED', name='case_status', schema='cases'), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('owning_jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('grouping_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_ref', name='uq_case_public_ref'),
    schema='cases'
    )
    op.create_index('ix_case_assigned', 'case', ['assigned_to_id'], unique=False, schema='cases')
    op.create_index('ix_case_opened_at', 'case', ['opened_at'], unique=False, schema='cases')
    op.create_index('ix_case_status', 'case', ['status'], unique=False, schema='cases')
    op.create_table('complaint',
    sa.Column('public_ref', sa.String(length=32), nullable=False),
    sa.Column('fraud_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('typology', sa.Enum('DIGITAL_ARREST', 'INVESTMENT_SCAM', 'UPI_COLLECT_FRAUD', 'CUSTOMER_CARE_IMPERSONATION', 'LOAN_APP_EXTORTION', 'JOB_TASK_FRAUD', 'SEXTORTION', 'OTHER', name='fraud_typology', schema='complaints'), nullable=False),
    sa.Column('reported_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('victim_jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('reported_beneficiary_account', sa.String(length=64), nullable=True),
    sa.Column('reported_beneficiary_ifsc', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.Enum('PUBLIC', 'INTERNAL', 'SENSITIVE', 'HIGHLY_SENSITIVE', 'RESTRICTED', name='classification', schema='core'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_ref', name='uq_complaint_public_ref'),
    sa.UniqueConstraint('source_system', 'source_record_id', name='uq_complaint_source_idempotency'),
    schema='complaints'
    )
    op.create_index('ix_complaint_jurisdiction', 'complaint', ['victim_jurisdiction_id'], unique=False, schema='complaints')
    op.create_index('ix_complaint_observed_at_id', 'complaint', ['observed_at', 'id'], unique=False, schema='complaints')
    op.create_index('ix_complaint_reported_at', 'complaint', ['reported_at'], unique=False, schema='complaints')
    op.create_index('ix_complaint_typology', 'complaint', ['typology'], unique=False, schema='complaints')
    op.create_index(op.f('ix_complaints_complaint_observed_at'), 'complaint', ['observed_at'], unique=False, schema='complaints')
    op.create_table('canonical_entity',
    sa.Column('public_ref', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.Enum('PUBLIC', 'INTERNAL', 'SENSITIVE', 'HIGHLY_SENSITIVE', 'RESTRICTED', name='classification', schema='core'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_ref', name='uq_canonical_entity_public_ref'),
    schema='entity'
    )
    op.create_index('ix_canonical_entity_kind', 'canonical_entity', ['kind'], unique=False, schema='entity')
    op.create_index('ix_canonical_entity_observed_at_id', 'canonical_entity', ['observed_at', 'id'], unique=False, schema='entity')
    op.create_index(op.f('ix_entity_canonical_entity_observed_at'), 'canonical_entity', ['observed_at'], unique=False, schema='entity')
    op.create_table('cash_out_endpoint',
    sa.Column('public_ref', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.Enum('ATM', 'AEPS_BC', 'BANK_BRANCH', 'POS_CASHBACK', 'MERCHANT_QR', 'PREPAID_GIFT', 'CRYPTO_P2P', name='cash_out_channel', schema='geo'), nullable=False),
    sa.Column('operator', sa.String(length=160), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('h3_r6', sa.String(length=16), nullable=True),
    sa.Column('h3_r7', sa.String(length=16), nullable=True),
    sa.Column('h3_r8', sa.String(length=16), nullable=True),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('cash_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.Enum('PUBLIC', 'INTERNAL', 'SENSITIVE', 'HIGHLY_SENSITIVE', 'RESTRICTED', name='classification', schema='core'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_ref', name='uq_endpoint_public_ref'),
    schema='geo'
    )
    op.create_index('ix_endpoint_channel', 'cash_out_endpoint', ['channel'], unique=False, schema='geo')
    op.create_index('ix_endpoint_geom', 'cash_out_endpoint', ['geom'], unique=False, schema='geo', postgresql_using='gist')
    op.create_index('ix_endpoint_h3_r7', 'cash_out_endpoint', ['h3_r7'], unique=False, schema='geo')
    op.create_index('ix_endpoint_h3_r8', 'cash_out_endpoint', ['h3_r8'], unique=False, schema='geo')
    op.create_index('ix_endpoint_observed_at_id', 'cash_out_endpoint', ['observed_at', 'id'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_cash_out_endpoint_observed_at'), 'cash_out_endpoint', ['observed_at'], unique=False, schema='geo')
    op.create_table('geographic_zone',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.Enum('PUBLIC', 'INTERNAL', 'SENSITIVE', 'HIGHLY_SENSITIVE', 'RESTRICTED', name='classification', schema='core'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['geo.geographic_zone.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_zone_code'),
    schema='geo'
    )
    op.create_index(op.f('ix_geo_geographic_zone_observed_at'), 'geographic_zone', ['observed_at'], unique=False, schema='geo')
    op.create_index('ix_geographic_zone_observed_at_id', 'geographic_zone', ['observed_at', 'id'], unique=False, schema='geo')
    op.create_index('ix_zone_boundary', 'geographic_zone', ['boundary'], unique=False, schema='geo', postgresql_using='gist')
    op.create_table('jurisdiction',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('level', sa.Enum('NATIONAL', 'STATE', 'RANGE', 'DISTRICT', 'POLICE_STATION', name='jurisdiction_level', schema='iam'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['iam.jurisdiction.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_jurisdiction_code'),
    schema='iam'
    )
    op.create_index('ix_jurisdiction_parent', 'jurisdiction', ['parent_id'], unique=False, schema='iam')
    op.create_table('audit_checkpoint',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('chain_head_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['audit.audit_event.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence', name='uq_audit_checkpoint_sequence'),
    schema='audit'
    )
    op.create_index('ix_audit_checkpoint_created', 'audit_checkpoint', ['created_at'], unique=False, schema='audit')
    op.create_table('case_complaint_link',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('owning_jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'complaint_id', name='uq_case_complaint'),
    schema='cases'
    )
    op.create_index('ix_case_complaint_complaint', 'case_complaint_link', ['complaint_id'], unique=False, schema='cases')
    op.create_table('intervention',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('intervention_type', sa.Enum('DEPLOY_TEAM', 'ALERT_LOCAL_BANK', 'ALERT_ATM_OPERATOR', 'REQUEST_FUND_BLOCK', 'REQUEST_CCTV', 'JURISDICTION_HANDOFF', 'NO_ACTION', name='intervention_type', schema='cases'), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('prediction_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=48), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_recovered', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cases'
    )
    op.create_index('ix_intervention_case', 'intervention', ['case_id', 'performed_at'], unique=False, schema='cases')
    op.create_index('ix_intervention_type', 'intervention', ['intervention_type'], unique=False, schema='cases')
    op.create_table('entity_resolution_decision',
    sa.Column('canonical_entity_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reversed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_entity_id'], ['entity.canonical_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['entity.entity_resolution_decision.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='entity'
    )
    op.create_index('ix_entity_decision_canonical', 'entity_resolution_decision', ['canonical_entity_id', 'decided_at'], unique=False, schema='entity')
    op.create_index('ix_entity_decision_decided_at', 'entity_resolution_decision', ['decided_at'], unique=False, schema='entity')
    op.create_table('entity_risk_score',
    sa.Column('canonical_entity_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=96), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_entity_id'], ['entity.canonical_entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='entity'
    )
    op.create_index('ix_entity_risk_entity_valid', 'entity_risk_score', ['canonical_entity_id', 'valid_from'], unique=False, schema='entity')
    op.create_index('ix_entity_risk_valid_from', 'entity_risk_score', ['valid_from'], unique=False, schema='entity')
    op.create_table('investigator',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('mfa_secret', sa.String(length=256), nullable=True),
    sa.Column('mfa_enrolled', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'NATIONAL_ANALYST', 'STATE_ANALYST', 'DISTRICT_INVESTIGATOR', 'BANK_PARTNER', 'AUDITOR', 'READ_ONLY_ANALYST', name='role', schema='iam'), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['iam.jurisdiction.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_investigator_username'),
    schema='iam'
    )
    op.create_table('break_glass_grant',
    sa.Column('investigator_id', sa.UUID(), nullable=False),
    sa.Column('justification', sa.String(length=1000), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('notified_party_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['iam.investigator.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigator_id'], ['iam.investigator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notified_party_id'], ['iam.investigator.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='iam'
    )
    op.create_index('ix_break_glass_active', 'break_glass_grant', ['investigator_id', 'expires_at'], unique=False, schema='iam')
    op.create_table('revoked_token',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('investigator_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigator_id'], ['iam.investigator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti', name='uq_revoked_token_jti'),
    schema='iam'
    )
    op.create_index('ix_revoked_token_expires_at', 'revoked_token', ['expires_at'], unique=False, schema='iam')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revoked_token_expires_at', table_name='revoked_token', schema='iam')
    op.drop_table('revoked_token', schema='iam')
    op.drop_index('ix_break_glass_active', table_name='break_glass_grant', schema='iam')
    op.drop_table('break_glass_grant', schema='iam')
    op.drop_table('investigator', schema='iam')
    op.drop_index('ix_entity_risk_valid_from', table_name='entity_risk_score', schema='entity')
    op.drop_index('ix_entity_risk_entity_valid', table_name='entity_risk_score', schema='entity')
    op.drop_table('entity_risk_score', schema='entity')
    op.drop_index('ix_entity_decision_decided_at', table_name='entity_resolution_decision', schema='entity')
    op.drop_index('ix_entity_decision_canonical', table_name='entity_resolution_decision', schema='entity')
    op.drop_table('entity_resolution_decision', schema='entity')
    op.drop_index('ix_intervention_type', table_name='intervention', schema='cases')
    op.drop_index('ix_intervention_case', table_name='intervention', schema='cases')
    op.drop_table('intervention', schema='cases')
    op.drop_index('ix_case_complaint_complaint', table_name='case_complaint_link', schema='cases')
    op.drop_table('case_complaint_link', schema='cases')
    op.drop_index('ix_audit_checkpoint_created', table_name='audit_checkpoint', schema='audit')
    op.drop_table('audit_checkpoint', schema='audit')
    op.drop_index('ix_jurisdiction_parent', table_name='jurisdiction', schema='iam')
    op.drop_table('jurisdiction', schema='iam')
    op.drop_index('ix_zone_boundary', table_name='geographic_zone', schema='geo', postgresql_using='gist')
    op.drop_index('ix_geographic_zone_observed_at_id', table_name='geographic_zone', schema='geo')
    op.drop_index(op.f('ix_geo_geographic_zone_observed_at'), table_name='geographic_zone', schema='geo')
    op.drop_table('geographic_zone', schema='geo')
    op.drop_index(op.f('ix_geo_cash_out_endpoint_observed_at'), table_name='cash_out_endpoint', schema='geo')
    op.drop_index('ix_endpoint_observed_at_id', table_name='cash_out_endpoint', schema='geo')
    op.drop_index('ix_endpoint_h3_r8', table_name='cash_out_endpoint', schema='geo')
    op.drop_index('ix_endpoint_h3_r7', table_name='cash_out_endpoint', schema='geo')
    op.drop_index('ix_endpoint_geom', table_name='cash_out_endpoint', schema='geo', postgresql_using='gist')
    op.drop_index('ix_endpoint_channel', table_name='cash_out_endpoint', schema='geo')
    op.drop_table('cash_out_endpoint', schema='geo')
    op.drop_index(op.f('ix_entity_canonical_entity_observed_at'), table_name='canonical_entity', schema='entity')
    op.drop_index('ix_canonical_entity_observed_at_id', table_name='canonical_entity', schema='entity')
    op.drop_index('ix_canonical_entity_kind', table_name='canonical_entity', schema='entity')
    op.drop_table('canonical_entity', schema='entity')
    op.drop_index(op.f('ix_complaints_complaint_observed_at'), table_name='complaint', schema='complaints')
    op.drop_index('ix_complaint_typology', table_name='complaint', schema='complaints')
    op.drop_index('ix_complaint_reported_at', table_name='complaint', schema='complaints')
    op.drop_index('ix_complaint_observed_at_id', table_name='complaint', schema='complaints')
    op.drop_index('ix_complaint_jurisdiction', table_name='complaint', schema='complaints')
    op.drop_table('complaint', schema='complaints')
    op.drop_index('ix_case_status', table_name='case', schema='cases')
    op.drop_index('ix_case_opened_at', table_name='case', schema='cases')
    op.drop_index('ix_case_assigned', table_name='case', schema='cases')
    op.drop_table('case', schema='cases')
    op.drop_index('ix_audit_event_resource', table_name='audit_event', schema='audit')
    op.drop_index('ix_audit_event_occurred_at', table_name='audit_event', schema='audit')
    op.drop_index('ix_audit_event_actor', table_name='audit_event', schema='audit')
    op.drop_table('audit_event', schema='audit')
    # ### end Alembic commands ###
