"""alerts persistence

Revision ID: eeb60a8f3965
Revises: 47a8554a2f45
Create Date: 2026-09-06 17:47:23.932283
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op


revision: str = 'eeb60a8f3965'
down_revision: str | None = '47a8554a2f45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('case_ref', sa.String(length=32), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity', schema='alerts'), nullable=True),
    sa.Column('raised', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('dedup_key', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='alerts'
    )
    op.create_index('ix_alert_case_ref', 'alert', ['case_ref'], unique=False, schema='alerts')
    op.create_index('ix_alert_jurisdiction_dedup_issued', 'alert', ['jurisdiction_id', 'dedup_key', 'issued_at'], unique=False, schema='alerts')
    op.create_index('ix_alert_jurisdiction_issued', 'alert', ['jurisdiction_id', 'issued_at'], unique=False, schema='alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_jurisdiction_issued', table_name='alert', schema='alerts')
    op.drop_index('ix_alert_jurisdiction_dedup_issued', table_name='alert', schema='alerts')
    op.drop_index('ix_alert_case_ref', table_name='alert', schema='alerts')
    op.drop_table('alert', schema='alerts')
    # ### end Alembic commands ###
    # Autogenerate creates the enum type with the table and does not drop it
    # again. Left behind, the next upgrade fails with "type alert_severity
    # already exists" — a downgrade that cannot be re-applied is not a
    # downgrade. `checkfirst` so this is safe on a database where the type was
    # never created.
    sa.Enum(name="alert_severity", schema="alerts").drop(op.get_bind(), checkfirst=True)
